spring:
  application:
    name: gulimall-coupon
  datasource:
    url: jdbc:mysql://121.36.25.190:3306/gulimall_sms
    username: root
    password: Cxf15364946594
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 121.36.25.190:8848 #nacos配置地址
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 5000
management:
  endpoints:
    web:
      exposure:
        include: '*'  #监控