spring:
  datasource:
    url: jdbc:mysql://121.36.25.190:3306/gulimall_sms
    username: root
    password: Cxf15364946594
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 5000