spring:
  cloud:
    alicloud:
      access-key: LTAI4G63bexdznLzPc3WXtuv
      secret-key: CKpFyGx6CPKpp70llwqISyo0gtLZzB
      oss:
        endpoint: http://oss-cn-shanghai.aliyuncs.com
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000